### ISSUE TITLE
Improve vagrant reload

### ISSUE THREAD

**Issue by FranklinChen** [TalkBank/shiny-vagrant#2]
`vagrant reload` currently takes forever because it reinstalls Shiny and reinstalls R packages, including C++ source code compilations. It would be nice if the provisioning script detected when these are already installed, in order to save several minutes.

**Comment by franklinr** [comment]
Ok, I've set it up to avoid reinstalling shiny.  How often does vagrant reload get called?  Does it happen whenever I change the github?  Or is it once a day?

**Comment by FranklinChen** [comment]
There's no automatic reload. When it looks to me like the configuration has changed, I just manually type `vagrant reload` and `vagrant provision` to make sure that everything is up to date. This happened when it looked like maybe new Linux or R packages were installed, for example. It looks like you just brute-force stopped all updates of any packages if Shiny has ever been installed, which seems strange because what if you want to add more logic to the provisioning, e.g. installation or keeping up to date of more files?

**Comment by franklinr** [comment]
Not really sure how to do that, but if you have any suggestions, feel free to change the files.  I'm using github and vagrant for the first time, so there is a lot that I don't know.

**Comment by franklinr** [comment]
Ok, made some changes.  apt-get will only install if there are changes.  The shiny server install code is hardwired, so we have to change that by hand.  Now the R libraries are only installed if they are not already installed.  But there is only one call to R, so should be faster.
