### ISSUE TITLE
Storage files

### ISSUE THREAD

**Issue by franklinr** [TalkBank/shiny-vagrant#3]
It seems like most of the shiny programs are working, so the last remaining issue is to get the files for the storage/ngrams and storage/csvfolders put on the machine (I sent them to brian).  I don't want to load them on github, since they take a lot of space.  So is it possible to put them on gandalf somewhere and I can link the ngrams and csvfolders to those locations?  Let me know what the options are.

**Comment by FranklinChen** [comment]
We have in a folder `~/shiny-vagrant-extras/` now.
