### ISSUE TITLE
gandalf is down

### ISSUE THREAD

**Issue by franklinr** [TalkBank/shiny-vagrant#4]
Just wondering if there is a reason that the shiny server on gandalf is down.  Apache seems to be working, so it seems to be up.  I'm wondering if one of my recent changes is the problem.  Even if shiny isn't working, the index.html page should still work, but it is not showing up.  Any thoughts?

**Comment by macw** [comment]
I have to restart it with all these new files.  I’m working on that now.  It looks like it could take a couple of hours to churn through the whole collection.  Hopefully, it would be back on line after that.

-Brian

**Comment by macw** [comment]
It seems to be back up now.  I had rebooted the machine, not realizing that this would kill various processes.  Franklin has restarted those processes now.  Eventually, I will need to learn what is needed to restart after a reboot.

—Brian

**Comment by macw** [comment]
I am receiving messages from this group, but I don’t know that this means I am receiving messages about actual commits to the repo.  Are those the same thing?

—Brian
