### ISSUE TITLE
Symbolic links in /srv/shiny-server/storage are broken

### ISSUE THREAD

**Issue by FranklinChen** [TalkBank/shiny-vagrant#8]
```
$ vagrant ssh
vagrant@ubuntu-artful:~$ ls /srv/shiny-server/storage
ls: cannot read symbolic link '/srv/shiny-server/storage/actualcsv': Invalid argument
ls: cannot read symbolic link '/srv/shiny-server/storage/csvcorpora': Invalid argument
ls: cannot read symbolic link '/srv/shiny-server/storage/ngrams': Invalid argument
actualcsv  bigspa.csv  csvcorpora  filesData-XML.rds  ngrams  storage  summaryChildes.rds
vagrant@ubuntu-artful:~$ ls -l /srv/shiny-server/storage/actualcsv
ls: cannot read symbolic link '/srv/shiny-server/storage/actualcsv': Invalid argument
lrwxr-xr-x 1 vagrant vagrant 43 Nov 18 16:59 /srv/shiny-server/storage/actualcsv
```

**Comment by franklinr** [comment]
I think the /vagrant folder is overwritten by github, so any link that you made will be deleted.
I've added made some link to /Volume/New, but can you check that the folders are correct.

**Comment by FranklinChen** [comment]
I don't understand because now it appears there's a conflict between `sync-from-extras.sh` and this hardcoded `/Volume/New` link.

Also, why is `/Volume/New` hardcoded into the `Vagrantfile`? You don't have a `/Volume/New' in your personal setup, do you?

**Comment by franklinr** [comment]
There is some problem with the existing setup, which may be due to the symbolic links that were created by hand.  If you prefer to put the /Volume/New links into sync-from-extras, that is fine with me.

**Comment by macw** [comment]
I think we are having coordination problems with this setup.  Would it be possible to set up a Skype phone call for Monday during which we could coordinate things better?  

One clear approach is for Franklin Chang could set up the whole system on his machine with a smaller set of actual data files with a vagrant container and material pulled from the GitHub repository and to verify locally that everything is working.  The one trick here is that he might not locally have the symbolic links necessary to store the huge files on /Volumes/New/shiny-vagrant-extras.  The location of these files and the presence of the relevant symbolic links in the /storage folder seems to be an ongoing problem.  Right now there are four symbolic links in storage, including one back to the non-existent location of /vagrant/storage.  I assume that one should be removed.  Then, over in /Volumes/New/shiny-vagrant-extras each of the three folders has an extraneous symbolic link pointing back to the symbolic link on the main disk.  

I can see two ways to fix these things.  One would be a Skype call.  I will be in the office tomorrow after 12:00 noon and all day Monday.  I am macwhinney on Skype.

The other way, which would be good in any case,  is for Chang to set up a working test version locally that makes use of something like the symbolic links that we need.  In that version, it would be good if there were some way to automatically recreate these symbolic links after git pull.

—Brian

**Comment by franklinr** [comment]
I think this is fixed
